// <auto-generated />
using System;
using KittyAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KittyAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221223145855_remove-email-and-role-fields")]
    partial class removeemailandrolefields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KittyAPI.Models.Stream", b =>
                {
                    b.Property<string>("StreamId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StreamTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreamerUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ThumbnailId")
                        .HasColumnType("int");

                    b.HasKey("StreamId");

                    b.HasIndex("StreamerUserId");

                    b.HasIndex("ThumbnailId");

                    b.ToTable("Streams");
                });

            modelBuilder.Entity("KittyAPI.Models.StreamUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StreamId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "StreamId");

                    b.HasIndex("StreamId");

                    b.ToTable("StreamUsers");
                });

            modelBuilder.Entity("KittyAPI.Models.Thumbnail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ThumbnailName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Thumbnails");
                });

            modelBuilder.Entity("KittyAPI.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KittyAPI.Models.Stream", b =>
                {
                    b.HasOne("KittyAPI.Models.User", "Streamer")
                        .WithMany()
                        .HasForeignKey("StreamerUserId");

                    b.HasOne("KittyAPI.Models.Thumbnail", "Thumbnail")
                        .WithMany()
                        .HasForeignKey("ThumbnailId");

                    b.Navigation("Streamer");

                    b.Navigation("Thumbnail");
                });

            modelBuilder.Entity("KittyAPI.Models.StreamUser", b =>
                {
                    b.HasOne("KittyAPI.Models.Stream", "Stream")
                        .WithMany("Participants")
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KittyAPI.Models.User", "User")
                        .WithMany("Streams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stream");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KittyAPI.Models.Stream", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("KittyAPI.Models.User", b =>
                {
                    b.Navigation("Streams");
                });
#pragma warning restore 612, 618
        }
    }
}
